### ISSUE TITLE
[Tracking] Towards registration

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/MLJFlow.jl#6]
Todo:

- [x] Add tests for simple pipelines (e.g. , `Standarizer |> DecisionTreeClassifer()`)
- [x] Add code coverage banner
- [x] Add keys for CompatHelper
- [x] Add example to readme
- [x] https://github.com/JuliaAI/MLJFlow.jl/issues/7
- [x] https://github.com/JuliaAI/MLJFlow.jl/issues/8
- [x] https://github.com/JuliaAI/MLJFlow.jl/pull/10

**Comment by pebeto** [comment]
All the requirements are done.
